version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.11.0/allure-commandline-2.11.0.zip
            unzip allure-commandline-2.11.0.zip
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod -R 777 ./allure-2.11.0/bin/
            pytest --alluredir=./allure-results
      - run:
          name: run report
          when: always
          command: |
            ./allure-2.11.0/bin/allure generate -c
      - store_artifacts:
          path: allure-report
          destination: allure-report
          when: always
